<a href="https://colab.research.google.com/github/Prabhjot410/Logistic-Regression/blob/main/exercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import copy, math

<h5>Ques 1 : Write a function to generate an m+1 dimensional data set, of size n, consisting of m continuous independent
variables (X) and one dependent binary variable (Y) </h5>

In [2]:
#genarating X 
n = 5   # no of rows
m = 4   #no of columns
First_col = np.ones((n,1))  #first column
rest_col = np.random.rand(n,m)
rest_col = np.random.rand(n,m)
X = np.append(First_col, rest_col, axis=1)
X

array([[1.        , 0.00235096, 0.45022017, 0.57143443, 0.35994137],
       [1.        , 0.73417676, 0.94149807, 0.65958905, 0.1540057 ],
       [1.        , 0.01413504, 0.85422323, 0.22300554, 0.30405927],
       [1.        , 0.9258145 , 0.55357091, 0.11946185, 0.7584408 ],
       [1.        , 0.82430394, 0.71914409, 0.24010788, 0.98456695]])

In [3]:
#Genrating Beta of m+1 dimensions
beta1 = np.random.rand(m+1)
#transpose beta
beta = beta1.reshape(m+1,1)
beta

array([[0.66358677],
       [0.63096207],
       [0.20129443],
       [0.75995167],
       [0.06011662]])

In [13]:
#generating z = x*Beta
Z = -np.matmul(X,beta)
Z

array([[-1.21159796],
       [-1.82685688],
       [-1.03220827],
       [-1.49555147],
       [-1.57011021]])

In [5]:
#generating y = 1/1+e^-(x*beta)
sigmoid = 1/(1+np.exp(-Z))
Y = np.where(sigmoid>0.5,1,0)
Y

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [6]:
#Creating the noise
# theta is prob of sucess
#t is trails
theta, t = .7, 1 
s = np.random.binomial(t,theta,n)
noise = s.reshape(n,1)
noise

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [7]:
#flipping the value where the larger the value of θ, the greater is the noise.
Y_flipping = np.where((Y==1)&(noise==1), 0 , noise)
Y_flipping

array([[1],
       [1],
       [1],
       [1],
       [1]])

<h5>Ques 2:Write a function that learns the parameters of a logistic regression function<h5/> 

In [8]:
def compute_cost_logistic(X, y, w, b):

    m = X.shape[0]
    cost = 0.0
    for i in range(m):
        z_i = np.dot(X[i],w) + b
        f_wb_i = 1/(1+np.exp(-z_i))
        cost +=  -y[i]*np.log(f_wb_i) - (1-y[i])*np.log(1-f_wb_i)
             
    cost = cost / m
    return cost

In [9]:
compute_cost_logistic(X,Y_flipping,beta,b=0)

array([0.22114663])

In [15]:
def sigmoid(Z):
  sigmoid = 1/(1+np.exp(-Z))
  return sigmoid

In [16]:
def compute_gradient_logistic(X, y, w, b): 
   
    m,n = X.shape
    dj_dw = np.zeros((n,))                           
    dj_db = 0.

    for i in range(m):
        f_wb_i = sigmoid(np.dot(X[i],w) + b)          
        err_i  = f_wb_i  - y[i]                       
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err_i * X[i,j]      
        dj_db = dj_db + err_i
    dj_dw = dj_dw/m                                   
    dj_db = dj_db/m                                   
        
    return dj_db, dj_dw  

In [11]:
def gradient_descent(X, y, w_in, b_in, alpha, num_iters): 
   
    # An array to store cost J and w's at each iteration primarily for graphing later
    J_history = []
    w = copy.deepcopy(w_in)  #avoid modifying global w within function
    b = b_in
    
    for i in range(num_iters):
        # Calculate the gradient and update the parameters
        dj_db, dj_dw = compute_gradient_logistic(X, y, w, b)   

        # Update Parameters using w, b, alpha and gradient
        w = w - alpha * dj_dw               
        b = b - alpha * dj_db               
      
        # Save cost J at each iteration
        if i<100000:      # prevent resource exhaustion 
            J_history.append( compute_cost_logistic(X, y, w, b) )

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i% math.ceil(num_iters / 10) == 0:
            print(f"Iteration {i:4d}: Cost {J_history[-1]}   ")
        
    return w, b, J_history      

In [17]:
w_tmp  = np.zeros_like(X[0])
b_tmp  = 0.
alph = 0.1
iters = 10000

w_out, b_out, _ = gradient_descent(X,Y_flipping, w_tmp, b_tmp, alph, iters) 
print(f"\nupdated parameters: w:{w_out}, b:{b_out}")

Iteration    0: Cost [0.61777041]   
Iteration 1000: Cost [0.00347143]   
Iteration 2000: Cost [0.00174206]   
Iteration 3000: Cost [0.00116439]   
Iteration 4000: Cost [0.00087502]   
Iteration 5000: Cost [0.00070112]   
Iteration 6000: Cost [0.00058504]   
Iteration 7000: Cost [0.00050203]   
Iteration 8000: Cost [0.0004397]   
Iteration 9000: Cost [0.00039118]   

updated parameters: w:[2.69356191 0.98998409 1.82229533 1.02022375 1.23931786], b:[2.69356191]
